apiVersion: v1
kind: Secret
metadata:
  name: console-app-secret
type: Opaque
data:
  httpusername: aHA= # hp (from DummyService/server.js) # Base64 encoded username
  httppassword: YWxvaG9tb3Jh  # alhomora (from DummyService/server.js) # Base64 encoded password