apiVersion: v1
kind: ConfigMap
metadata:
  name: console-app-config
data:
  ENDPOINT_TYPE: "http" # http or sql
  AUTH_TYPE: "httpbasic" # httpbasic or sqlbasic
  REQUEST_INTERVAL_SECONDS: "10"
  DSS_KEY: "quality"
  MQTT_HOST: "aio-mq-dmqtt-frontend.default.svc.cluster.local" # kubectl get pods => aio-mq-dmqtt-frontend-0 => the mqtt client (dss context app, in this case) would connect to the MQ frontend # The ip of the BROKER API. Replace with your own value.
  MQTT_CLIENT_ID: "dss-console-app" # The client ID of the MQTT client. Replace with your own value.
  MQTT_PORT: "1883" # Connecting as non-TLS

  HTTP_BASE_URL: "http://my-backend-api-s.default.svc.cluster.local:80" # backend-api.yaml => Service => metadata.name, # The URL of the backend API. Replace with your own value.
  HTTP_PATH: "contexts/quality" # The path of the API endpoint. Replace with your own value.

  USE_TLS: "false"