apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-api-d
  labels:
    app: my-backend-api-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-api-d
  template:
    metadata:
      labels:
        app: my-backend-api-d
    spec:
      containers:
      - name: my-backend-api-d
        image: my-backend-api # Image imported directly to the cluster
        imagePullPolicy: Never # Image imported directly to the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-api-s # This Service would be accessible at my-backend-api-s.default.svc.cluster.local:80 (<service-name>.<namespace>.svc.cluster.local:<port>)
  labels:
    app: my-backend-api-d 
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80  # This is the port that the Service listens on
    targetPort: 80  # This is the port that the Pod labeled my-backend-api-d listens on
  selector:
    app: my-backend-api-d # This is the label of the Pod that this Service points to